version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo123
    ports:
      - "3306:3306"
    volumes:
      - ./db_demo:/var/lib/mysql